name: pzero
channels:
  - conda-forge
  - loop3d
  - defaults
dependencies:
  - affine=2.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.5=py38h91455d4_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alabaster=0.7.13=pyhd8ed1ab_0
  - altgraph=0.17.3=pyhd8ed1ab_0
  - aom=3.5.0=h63175ca_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - black=23.7.0=py38haa244fe_1
  - blackd=23.7.0=hd8ed1ab_1
  - blosc=1.21.4=hdccc3a2_0
  - boost-cpp=1.78.0=h9f4b32c_3
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_9
  - brotli-bin=1.0.9=hcfcfb64_9
  - brotli-python=1.0.9=py38hd3f51b4_9
  - bzip2=1.0.8=h8ffe710_4
  - c-blosc2=2.10.0=h183a6f4_0
  - ca-certificates=2023.5.7=h56e8100_0
  - cairo=1.16.0=hd694305_1014
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cfitsio=4.2.0=h9ebe7e4_0
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.6=win_pyh7428d3b_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cmocean=3.0.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.0.1=pyhd8ed1ab_0
  - colorspacious=1.1.2=pyh24bf2e0_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.1.0=py38hb1fd069_0
  - curl=8.1.2=h68f0423_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dav1d=1.2.0=hcfcfb64_0
  - debugpy=1.6.7=py38hd3f51b4_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - deprecated=1.2.14=pyh1a96a4e_0
  - docutils=0.18.1=py38haa244fe_1
  - double-conversion=3.2.0=h63175ca_1
  - eigen=3.4.1=h91493d7_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - exceptiongroup=1.1.2=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h63175ca_1
  - ezdxf=1.0.3=py38hb1fd069_0
  - ffmpeg=5.1.2=gpl_h5037a79_109
  - fiona=1.9.3=py38h2489377_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.41.0=py38h91455d4_0
  - freetype=2.12.1=h546665d_1
  - freexl=1.0.6=h67ca5e6_1
  - frozenlist=1.4.0=py38h91455d4_0
  - future=0.18.3=pyhd8ed1ab_0
  - gdal=3.6.3=py38h5a6f081_0
  - geopandas=0.13.2=pyhd8ed1ab_1
  - geopandas-base=0.13.2=pyha770c72_1
  - geos=3.11.1=h1537add_0
  - geotiff=1.7.1=hb4c6682_7
  - gettext=0.21.1=h5728263_0
  - giflib=5.2.1=h64bf75a_3
  - gl2ps=1.4.2=h0597ee9_0
  - glew=2.1.0=h39d44d4_2
  - glib=2.76.4=h12be248_0
  - glib-tools=2.76.4=h12be248_0
  - gst-plugins-base=1.22.4=h001b923_1
  - gstreamer=1.22.4=hb4038d2_1
  - hdf4=4.2.15=h1334946_6
  - hdf5=1.12.2=nompi_h57737ce_101
  - icu=70.1=h0e60522_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs=2023.1.23=py38h590f084_1
  - imageio=2.31.1=pyh24c5eb1_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib-resources=6.0.0=pyhd8ed1ab_1
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.0=pyhd8ed1ab_1
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=h57928b3_46319
  - ipydatawidgets=4.3.2=pyhc268e32_0
  - ipykernel=6.24.0=pyh6817e22_0
  - ipython=8.12.2=pyh08f2357_0
  - ipywidgets=8.0.7=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.0=pyhd8ed1ab_1
  - jsoncpp=1.9.5=h2d74725_1
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py38haa244fe_0
  - jupyterlab_widgets=3.0.8=pyhd8ed1ab_0
  - jxrlib=1.1=h8ffe710_2
  - kealib=1.5.0=h61be68b_0
  - kiwisolver=1.4.4=py38hb1fd069_1
  - krb5=1.20.1=heb0366b_0
  - laspy=2.3.0=pyha21a80b_0
  - lazy_loader=0.2=pyhd8ed1ab_0
  - lcms2=2.15=h3e3b177_1
  - lerc=4.0.0=h63175ca_0
  - libaec=1.0.6=h63175ca_1
  - libavif=0.11.1=h5da7522_1
  - libblas=3.9.0=17_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_9
  - libbrotlidec=1.0.9=hcfcfb64_9
  - libbrotlienc=1.0.9=hcfcfb64_9
  - libcblas=3.9.0=17_win64_mkl
  - libclang=15.0.7=default_h77d9078_2
  - libclang13=15.0.7=default_h77d9078_2
  - libcurl=8.1.2=h68f0423_0
  - libdeflate=1.17=hcfcfb64_0
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.2=h8ffe710_5
  - libgdal=3.6.3=h1443b5b_0
  - libglib=2.76.4=he8f3873_0
  - libhwloc=2.9.1=h51c2c0f_0
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=2.1.5.1=hcfcfb64_0
  - libkml=1.3.0=hf2ab4e4_1015
  - liblapack=3.9.0=17_win64_mkl
  - libnetcdf=4.9.1=nompi_h83fa41b_102
  - libogg=1.3.4=h8ffe710_1
  - libopus=1.3.1=h8ffe710_1
  - libpng=1.6.39=h19919ed_0
  - libpq=15.3=ha9684e8_0
  - librttopo=1.1.0=he22b5cd_12
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.0.1=hfdcade0_23
  - libsqlite=3.42.0=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libtheora=1.1.1=h8d14728_1005
  - libtiff=4.5.0=hc3b8658_5
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.3.1=hcfcfb64_0
  - libxcb=1.15=hcd874cb_0
  - libxml2=2.10.4=hc3477c8_0
  - libxslt=1.1.37=h0192164_0
  - libzip=1.9.2=h519de47_1
  - libzlib=1.2.13=hcfcfb64_5
  - libzopfli=1.0.3=h0e60522_0
  - loguru=0.7.0=py38haa244fe_0
  - loopstructural=v1.5.10=py38h4cae798_0
  - lxml=4.9.2=py38h8e95c58_0
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - macholib=1.16.2=pyhd8ed1ab_0
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markupsafe=2.1.3=py38h91455d4_0
  - matplotlib-base=3.7.2=py38h2d9580e_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2022.1.0=h6a75c08_874
  - mplstereonet=0.6.2=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.4=py38h91455d4_0
  - munch=4.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - nlohmann_json=3.11.2=h39d44d4_0
  - numpy=1.24.4=py38h1d91fd2_0
  - openh264=2.3.1=h63175ca_2
  - openjpeg=2.5.0=ha2aaf27_2
  - openpyxl=3.1.2=py38h91455d4_0
  - openssl=3.1.1=hcfcfb64_1
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=1.5.3=py38h5846ac1_1
  - param=1.13.0=pyh1a96a4e_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.11.1=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=h17e33f8_0
  - pefile=2023.2.7=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py38ha7eb54a_1
  - pip=23.2=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - platformdirs=3.9.1=pyhd8ed1ab_0
  - pluggy=1.2.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - poppler=23.03.0=h934c637_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.3=hd87cd2b_0
  - proj=9.1.1=heca977f_2
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py38h91455d4_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pugixml=1.11.4=h63175ca_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyinstaller=5.13.0=py38ha959d8a_0
  - pyinstaller-hooks-contrib=2023.5=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.5.0=py38h27cf8d4_0
  - pyqt=5.15.7=py38hd6c051e_3
  - pyqt5-sip=12.11.0=py38hd3f51b4_3
  - pysocks=1.7.1=pyh0701188_6
  - pytest=7.4.0=pyhd8ed1ab_0
  - python=3.8.17=h4de0772_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=3_cp38
  - pythreejs=2.4.2=pyh1d7be83_0
  - pytz=2023.3=pyhd8ed1ab_0
  - pyvista=0.41.0=pyhd8ed1ab_0
  - pyvistaqt=0.11.0=pyhd8ed1ab_0
  - pywavelets=1.4.1=py38hbaf524b_0
  - pywin32=304=py38hd3f51b4_2
  - pywin32-ctypes=0.2.2=py38haa244fe_0
  - pyyaml=6.0=py38h91455d4_5
  - pyzmq=25.1.0=py38ha85f68a_0
  - qt-main=5.15.8=h88fe7eb_7
  - qtpy=2.3.1=pyhd8ed1ab_0
  - rasterio=1.3.6=py38h0c735b1_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rtree=1.0.1=py38h8b54edf_1
  - scikit-image=0.21.0=py38hd3f51b4_0
  - scikit-learn=1.3.0=py38h763eb3e_0
  - scipy=1.10.1=py38h1aea9ed_3
  - scooby=0.7.2=pyhd8ed1ab_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=68.0.0=pyhd8ed1ab_0
  - shapely=1.8.5=py38h9c0aba1_2
  - sip=6.7.9=py38hd3f51b4_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hfb803bf_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - sphinx=6.2.1=pyhd8ed1ab_0
  - sphinx_rtd_theme=1.2.2=pyha770c72_0
  - sphinxcontrib-applehelp=1.0.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.1=pyhd8ed1ab_0
  - sphinxcontrib-jquery=4.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - sqlite=3.42.0=hcfcfb64_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py38h634f036_1
  - svt-av1=1.4.1=h63175ca_0
  - tbb=2021.9.0=h91493d7_0
  - tbb-devel=2021.9.0=h91493d7_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tifffile=2023.7.10=pyhd8ed1ab_0
  - tiledb=2.13.2=h3132609_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.2=py38h91455d4_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - traittypes=0.2.1=pyh9f0ad1d_2
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.0.0=py38h91455d4_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - utfcpp=3.2.3=h57928b3_0
  - vc=14.3=h64f974e_17
  - vc14_runtime=14.36.32532=hfdfe4a8_17
  - vedo=2023.4.6=pyhd8ed1ab_0
  - vs2015_runtime=14.36.32532=h05e6639_17
  - vtk=9.2.6=qt_py38h48dd242_201
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.8=pyhd8ed1ab_0
  - win32_setctime=1.1.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - wrapt=1.15.0=py38h91455d4_0
  - wslink=1.11.1=pyhd8ed1ab_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xarray=2023.1.0=pyhd8ed1ab_0
  - xerces-c=3.2.4=h63175ca_2
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2023.7.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - yarl=1.9.2=py38h91455d4_0
  - zeromq=4.3.4=h0e60522_1
  - zfp=1.0.0=h63175ca_3
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_5
  - zlib-ng=2.0.7=hcfcfb64_0
  - zstd=1.5.2=h12be248_7
prefix: C:\Users\bistek\anaconda3\envs\pzero
